# Generated by Django 6.0.3 on 2026-04-15 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bom',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='bom',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bom',
            name='bom_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bom',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boms', to='accounts.brand'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='catalogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boms', to='accounts.catalogue'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boms', to='accounts.category'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='bom',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boms', to='accounts.maincategory'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bom',
            name='pattern_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boms', to='accounts.patterntype'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='size_type',
            field=models.CharField(blank=True, choices=[('regular', 'Regular'), ('plus', 'Plus'), ('kids', 'Kids'), ('combo', 'Combo')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='bom',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boms', to='accounts.subcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='bom',
            unique_together={('owner', 'bom_code'), ('owner', 'sku')},
        ),
        migrations.CreateModel(
            name='BOMAccessoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('accessory', models.ForeignKey(limit_choices_to={'material_kind': 'trim'}, on_delete=django.db.models.deletion.PROTECT, related_name='bom_accessory_items', to='accounts.material')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_items', to='accounts.bom')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_accessory_items', to='accounts.materialunit')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BOMMaterialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_items', to='accounts.bom')),
                ('material', models.ForeignKey(limit_choices_to={'material_kind__in': ['yarn', 'greige', 'finished', 'trim']}, on_delete=django.db.models.deletion.PROTECT, related_name='bom_material_items', to='accounts.material')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_material_items', to='accounts.materialunit')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
