# Generated by Django 6.0.3 on 2026-04-15 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_bom_options_bom_owner_bom_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='character_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='bom',
            name='color',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='bom',
            name='drawcord',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='bom',
            name='license_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='bom',
            name='maintenance_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bom',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bom',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bom',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bom',
            name='tie_dye_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='BOMImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bom/%Y/%m/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.bom')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
