# Generated by Django 6.0 on 2026-01-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_jobbertype_jobber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('YARN', 'Yarn'), ('GREIGE', 'Greige'), ('FINISHED', 'Finished'), ('TRIM', 'Trim')], default='YARN', max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('remarks', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/')),
                ('active', models.BooleanField(default=True)),
                ('yarn_type', models.CharField(blank=True, max_length=120)),
                ('yarn_sub_type', models.CharField(blank=True, max_length=120)),
                ('yarn_other', models.CharField(blank=True, max_length=160)),
                ('yarn_count_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('greige_type', models.CharField(blank=True, max_length=120)),
                ('greige_sub_type', models.CharField(blank=True, max_length=120)),
                ('greige_other', models.CharField(blank=True, max_length=160)),
                ('greige_gsm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('finished_type', models.CharField(blank=True, max_length=120)),
                ('finished_sub_type', models.CharField(blank=True, max_length=120)),
                ('finished_other', models.CharField(blank=True, max_length=160)),
                ('finished_shade', models.CharField(blank=True, max_length=120)),
                ('trim_type', models.CharField(blank=True, max_length=120)),
                ('trim_sub_type', models.CharField(blank=True, max_length=120)),
                ('trim_other', models.CharField(blank=True, max_length=160)),
                ('trim_size', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
