# Generated by Django 6.0 on 2026-01-05 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={},
        ),
        migrations.RemoveField(
            model_name='material',
            name='active',
        ),
        migrations.RemoveField(
            model_name='material',
            name='code',
        ),
        migrations.RemoveField(
            model_name='material',
            name='finished_other',
        ),
        migrations.RemoveField(
            model_name='material',
            name='finished_shade',
        ),
        migrations.RemoveField(
            model_name='material',
            name='finished_sub_type',
        ),
        migrations.RemoveField(
            model_name='material',
            name='finished_type',
        ),
        migrations.RemoveField(
            model_name='material',
            name='greige_gsm',
        ),
        migrations.RemoveField(
            model_name='material',
            name='greige_other',
        ),
        migrations.RemoveField(
            model_name='material',
            name='greige_sub_type',
        ),
        migrations.RemoveField(
            model_name='material',
            name='greige_type',
        ),
        migrations.RemoveField(
            model_name='material',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='material',
            name='trim_other',
        ),
        migrations.RemoveField(
            model_name='material',
            name='trim_size',
        ),
        migrations.RemoveField(
            model_name='material',
            name='trim_sub_type',
        ),
        migrations.RemoveField(
            model_name='material',
            name='trim_type',
        ),
        migrations.RemoveField(
            model_name='material',
            name='yarn_count_contribution',
        ),
        migrations.RemoveField(
            model_name='material',
            name='yarn_other',
        ),
        migrations.RemoveField(
            model_name='material',
            name='yarn_sub_type',
        ),
        migrations.RemoveField(
            model_name='material',
            name='yarn_type',
        ),
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('yarn', 'Yarn'), ('greige', 'Greige'), ('finished', 'Finished Material'), ('trim', 'Trim')], default='yarn', max_length=16),
        ),
        migrations.AddField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='materials/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='FinishedDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fabric_type', models.CharField(max_length=120)),
                ('finish_type', models.CharField(choices=[('dyed', 'Dyed'), ('printed', 'Printed'), ('coated', 'Coated'), ('washed', 'Washed'), ('other', 'Other')], max_length=20)),
                ('gsm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('end_use', models.CharField(blank=True, max_length=120)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finished', to='accounts.material')),
            ],
        ),
        migrations.CreateModel(
            name='GreigeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_type', models.CharField(max_length=120)),
                ('gsm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('construction', models.CharField(blank=True, max_length=120)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='greige', to='accounts.material')),
            ],
        ),
        migrations.CreateModel(
            name='TrimDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trim_type', models.CharField(choices=[('Button', 'Button'), ('Zipper', 'Zipper'), ('Label', 'Label'), ('Elastic', 'Elastic'), ('Thread', 'Thread'), ('Hook', 'Hook'), ('Other', 'Other')], max_length=80)),
                ('size', models.CharField(blank=True, max_length=60)),
                ('color', models.CharField(blank=True, max_length=60)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trim', to='accounts.material')),
            ],
        ),
        migrations.CreateModel(
            name='YarnDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yarn_type', models.CharField(max_length=80)),
                ('yarn_subtype', models.CharField(blank=True, max_length=80)),
                ('count_denier', models.CharField(blank=True, max_length=40)),
                ('color', models.CharField(blank=True, max_length=60)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yarn', to='accounts.material')),
            ],
        ),
    ]
