# Generated by Django 6.0.3 on 2026-04-15 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bom_character_name_bom_color_bom_drawcord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='greigepurchaseorderitem',
            name='count',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='greigepurchaseorderitem',
            name='dia',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='greigepurchaseorderitem',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='greigepurchaseorderitem',
            name='gauge',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='greigepurchaseorderitem',
            name='gsm',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='greigepurchaseorderitem',
            name='hsn_code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='greigepurchaseorderitem',
            name='material',
            field=models.ForeignKey(blank=True, limit_choices_to={'material_kind': 'greige'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='greige_po_items', to='accounts.material'),
        ),
        migrations.AddField(
            model_name='greigepurchaseorderitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='greigepurchaseorderitem',
            name='rolls',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='greigepurchaseorderitem',
            name='sl',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='greigepurchaseorderitem',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='greigepurchaseorderitem',
            name='fabric_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
