# Generated by Django 6.0.3 on 2026-04-15 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_greigepurchaseorderitem_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='accounts.bom')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_expense_items', to='accounts.expense')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BOMJobberDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobber_details', to='accounts.bom')),
                ('jobber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_jobber_details', to='accounts.jobber')),
                ('jobber_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_jobber_detail_types', to='accounts.jobbertype')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BOMJobberTypeProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobber_type_processes', to='accounts.bom')),
                ('jobber_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_jobber_type_processes', to='accounts.jobbertype')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
