# Generated by Django 6.0.3 on 2026-04-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bomexpenseitem_bomjobberdetail_bomjobbertypeprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='damage_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='bom',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
    ]
