# Generated by Django 6.0.3 on 2026-04-15 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_bom_damage_percent_bom_final_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='greigepoinward',
            options={},
        ),
        migrations.AddField(
            model_name='greigepoinward',
            name='inward_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='greige_inwards', to='accounts.inwardtype'),
        ),
    ]
