# Generated by Django 6.0.3 on 2026-04-15 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_greigepoinward_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyeingmateriallinkdetail',
            name='finished_material',
            field=models.ForeignKey(blank=True, limit_choices_to={'material_kind': 'finished'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dyeing_link_details', to='accounts.material'),
        ),
        migrations.AlterField(
            model_name='dyeingmateriallink',
            name='material',
            field=models.ForeignKey(limit_choices_to={'material_kind': 'greige'}, on_delete=django.db.models.deletion.PROTECT, related_name='dyeing_material_links', to='accounts.material'),
        ),
        migrations.AlterField(
            model_name='dyeingmateriallink',
            name='material_type',
            field=models.ForeignKey(limit_choices_to={'material_kind': 'greige'}, on_delete=django.db.models.deletion.PROTECT, related_name='dyeing_material_links', to='accounts.materialtype'),
        ),
    ]
