# Generated by Django 6.0.3 on 2026-04-15 19:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_dyeingmateriallinkdetail_finished_material_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='dyeingpurchaseorder',
            old_name='available_qty',
            new_name='after_discount_value',
        ),
        migrations.RemoveField(
            model_name='dyeingpurchaseorder',
            name='delivery_period',
        ),
        migrations.RemoveField(
            model_name='dyeingpurchaseorder',
            name='delivery_schedule',
        ),
        migrations.RemoveField(
            model_name='dyeingpurchaseorder',
            name='director',
        ),
        migrations.RemoveField(
            model_name='dyeingpurchaseorder',
            name='validity_period',
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorder',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorder',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorder',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorder',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorder',
            name='others',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorder',
            name='tcs_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorder',
            name='terms_conditions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorderitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorderitem',
            name='dyeing_master_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dyeing_po_items', to='accounts.dyeingmateriallinkdetail'),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorderitem',
            name='dyeing_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorderitem',
            name='dyeing_other_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dyeing_po_items', to='accounts.dyeingothercharge'),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorderitem',
            name='dyeing_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorderitem',
            name='finished_material',
            field=models.ForeignKey(blank=True, limit_choices_to={'material_kind': 'finished'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dyeing_po_finished_items', to='accounts.material'),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorderitem',
            name='job_work_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorderitem',
            name='line_final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorderitem',
            name='line_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorderitem',
            name='other_charge_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorderitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorderitem',
            name='remaining_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorderitem',
            name='rolls',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorderitem',
            name='total_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorderitem',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dyeingpurchaseorderitem',
            name='fabric_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_no', models.CharField(max_length=30)),
                ('program_date', models.DateField(default=django.utils.timezone.localdate)),
                ('total_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ratio', models.CharField(blank=True, default='', max_length=120)),
                ('damage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='accounts.bom')),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='accounts.firm')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('owner', 'program_no')},
            },
        ),
        migrations.CreateModel(
            name='ProgramJobberDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('jobber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_jobber_rows', to='accounts.jobber')),
                ('jobber_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_jobber_type_rows', to='accounts.jobbertype')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobber_rows', to='accounts.program')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
