# Generated by Django 6.0 on 2026-01-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_material_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_kind',
            field=models.CharField(choices=[('yarn', 'Yarn'), ('greige', 'Greige'), ('finished', 'Finished Material'), ('trim', 'Trim')], default='yarn', max_length=16),
        ),
    ]
