# Generated by Django 6.0.3 on 2026-04-15 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_available_qty_dyeingpurchaseorder_after_discount_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='cutting_invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='program',
            name='glt_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='program',
            name='glt_on_100_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='program',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='program',
            name='stitching_invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='programjobberdetail',
            name='inward_qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='programjobberdetail',
            name='issued_qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='ProgramSizeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(choices=[('CQ', 'CQ'), ('FQ', 'FQ'), ('DQ', 'DQ'), ('FQ-DQ', 'FQ-DQ'), ('TP', 'TP')], max_length=20)),
                ('xs_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('s_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('m_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('l_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('xl_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('xxl_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_rows', to='accounts.program')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('program', 'line_name')},
            },
        ),
    ]
