# Generated by Django 6.0 on 2026-01-07 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_material_material_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_shade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='accounts.materialshade'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_kind',
            field=models.CharField(choices=[('yarn', 'Yarn'), ('greige', 'Greige'), ('finished', 'Finished'), ('trim', 'Trim')], default='yarn', max_length=16),
        ),
    ]
