# Generated by Django 6.0.3 on 2026-04-15 21:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_dyeingpurchaseorder_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='finishing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DispatchChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challan_no', models.CharField(max_length=30)),
                ('challan_date', models.DateField(default=django.utils.timezone.localdate)),
                ('driver_name', models.CharField(blank=True, default='', max_length=120)),
                ('lr_no', models.CharField(blank=True, default='', max_length=60)),
                ('transport_name', models.CharField(blank=True, default='', max_length=150)),
                ('vehicle_no', models.CharField(blank=True, default='', max_length=30)),
                ('remarks', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_challans', to='accounts.client')),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_challans', to='accounts.firm')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_challans', to='accounts.program')),
            ],
            options={
                'ordering': ['-challan_date', '-id'],
                'unique_together': {('owner', 'challan_no')},
            },
        ),
    ]
