# Generated by Django 6.0 on 2026-01-08 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_material_material_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialtype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='materialtype',
            name='material_kind',
            field=models.CharField(choices=[('yarn', 'Yarn'), ('greige', 'Greige'), ('finished', 'Finished'), ('trim', 'Trim')], default='yarn', max_length=16),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_kind',
            field=models.CharField(choices=[('yarn', 'Yarn'), ('greige', 'Greige'), ('finished', 'Finished'), ('trim', 'Trim')], default='yarn', max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='materialtype',
            unique_together={('owner', 'material_kind', 'name')},
        ),
    ]
