# Generated by Django 6.0.3 on 2026-04-15 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_program_finishing_date_dispatchchallan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatchchallan',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='greigepurchaseorder',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='dispatchchallan',
            name='lr_no',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='dispatchchallan',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_challans', to='accounts.program'),
        ),
        migrations.AlterField(
            model_name='dispatchchallan',
            name='vehicle_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
