# Generated by Django 6.0.3 on 2026-04-16 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_dispatchchallan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='greigepurchaseorder',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='greige_purchase_orders', to='accounts.firm'),
        ),
    ]
