# Generated by Django 6.0.3 on 2026-03-25 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_materialshade_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('contact_person', models.CharField(blank=True, default='', max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('gst_number', models.CharField(blank=True, default='', max_length=15)),
                ('address', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='YarnPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('po_number', models.CharField(blank=True, default='', max_length=30)),
                ('po_date', models.DateField()),
                ('cancel_date', models.DateField(blank=True, null=True)),
                ('shipping_address', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('terms_conditions', models.TextField(blank=True, default='')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('after_discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('others', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst_percent', models.DecimalField(decimal_places=2, default=2.5, max_digits=6)),
                ('sgst_percent', models.DecimalField(decimal_places=2, default=2.5, max_digits=6)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yarn_purchase_orders', to='accounts.firm')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yarn_purchase_orders', to='accounts.vendor')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='YarnPurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dia', models.CharField(blank=True, default='', max_length=30)),
                ('gauge', models.CharField(blank=True, default='', max_length=30)),
                ('rolls', models.CharField(blank=True, default='', max_length=30)),
                ('count', models.CharField(blank=True, default='', max_length=30)),
                ('gsm', models.CharField(blank=True, default='', max_length=30)),
                ('sl', models.CharField(blank=True, default='', max_length=30)),
                ('hsn_code', models.CharField(blank=True, default='', max_length=30)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yarn_po_items', to='accounts.material')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.yarnpurchaseorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
