# Generated by Django 6.0.3 on 2026-04-16 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_greigepurchaseorder_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyeingpoinward',
            name='inward_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dyeing_inwards', to='accounts.inwardtype'),
        ),
        migrations.AddField(
            model_name='dyeingpoinward',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dyeing_inwards', to='accounts.vendor'),
        ),
        migrations.AddField(
            model_name='dyeingpoinwarditem',
            name='accepted_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dyeingpoinwarditem',
            name='actual_gsm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='dyeingpoinwarditem',
            name='actual_rolls',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dyeingpoinwarditem',
            name='actual_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='dyeingpoinwarditem',
            name='batch_no',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='dyeingpoinwarditem',
            name='dye_lot_no',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='dyeingpoinwarditem',
            name='hold_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dyeingpoinwarditem',
            name='qc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('partial', 'Partial'), ('hold', 'Hold'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='dyeingpoinwarditem',
            name='received_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dyeingpoinwarditem',
            name='rejected_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dyeingpoinwarditem',
            name='shade_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorderitem',
            name='actual_output_qty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual inward/produced dyed quantity.', max_digits=12),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorderitem',
            name='balance_output_qty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining balance quantity against expected/actual output.', max_digits=12),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorderitem',
            name='expected_loss_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Expected process loss percentage.', max_digits=6),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorderitem',
            name='expected_output_qty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Expected output quantity after process loss.', max_digits=12),
        ),
        migrations.AddField(
            model_name='dyeingpurchaseorderitem',
            name='source_input_qty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Source greige/input quantity received for dyeing.', max_digits=12),
        ),
    ]
