# Generated by Django 6.0.3 on 2026-03-31 12:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_yarnpurchaseorder_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='yarnpurchaseorder',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='YarnPOInward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inward_number', models.CharField(max_length=30, unique=True)),
                ('inward_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inwards', to='accounts.yarnpurchaseorder')),
            ],
            options={
                'ordering': ['-inward_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='YarnPOInwardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('inward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.yarnpoinward')),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inward_items', to='accounts.yarnpurchaseorderitem')),
            ],
            options={
                'unique_together': {('inward', 'po_item')},
            },
        ),
    ]
