# Generated by Django 6.0.3 on 2026-04-16 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_dyeingpoinward_inward_type_dyeingpoinward_vendor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_started', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='start_record', to='accounts.program')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramStartFabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('count', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pp_count', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lot_no', models.CharField(blank=True, default='', max_length=150)),
                ('lot_count', models.PositiveIntegerField(default=0)),
                ('available_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('used_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_start_fabrics', to='accounts.material')),
                ('start_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_rows', to='accounts.programstart')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_start_fabrics', to='accounts.materialunit')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramStartJobber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobber_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allocation_date', models.DateField(blank=True, null=True)),
                ('invoice_no', models.CharField(blank=True, default='', max_length=100)),
                ('invoice_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('jobber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_start_jobbers', to='accounts.jobber')),
                ('jobber_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_start_jobber_types', to='accounts.jobbertype')),
                ('start_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobber_rows', to='accounts.programstart')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramStartSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=20)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('start_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_rows', to='accounts.programstart')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
