# Generated by Django 6.0.3 on 2026-04-01 09:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_yarnpurchaseorder_rejection_reason_yarnpoinward_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GreigePurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('po_number', models.CharField(blank=True, default='', max_length=30)),
                ('po_date', models.DateField(default=django.utils.timezone.localdate)),
                ('remarks', models.TextField(blank=True, default='')),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='greige_purchase_orders', to='accounts.firm')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source_yarn_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greige_pos', to='accounts.yarnpurchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='greige_purchase_orders', to='accounts.vendor')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GreigePurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_name', models.CharField(max_length=150)),
                ('yarn_name', models.CharField(blank=True, default='', max_length=150)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.greigepurchaseorder')),
                ('source_yarn_po_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_greige_items', to='accounts.yarnpurchaseorderitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
