# Generated by Django 6.0.3 on 2026-04-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_programstart_programstartfabric_programstartjobber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programstart',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='programstart',
            name='program',
        ),
        migrations.RemoveField(
            model_name='programstartfabric',
            name='start_record',
        ),
        migrations.RemoveField(
            model_name='programstartjobber',
            name='start_record',
        ),
        migrations.RemoveField(
            model_name='programstartfabric',
            name='material',
        ),
        migrations.RemoveField(
            model_name='programstartfabric',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='programstartjobber',
            name='jobber',
        ),
        migrations.RemoveField(
            model_name='programstartjobber',
            name='jobber_type',
        ),
        migrations.AlterField(
            model_name='dyeingpurchaseorderitem',
            name='actual_output_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dyeingpurchaseorderitem',
            name='balance_output_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dyeingpurchaseorderitem',
            name='expected_loss_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='dyeingpurchaseorderitem',
            name='expected_output_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dyeingpurchaseorderitem',
            name='source_input_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.DeleteModel(
            name='ProgramStartSize',
        ),
        migrations.DeleteModel(
            name='ProgramStart',
        ),
        migrations.DeleteModel(
            name='ProgramStartFabric',
        ),
        migrations.DeleteModel(
            name='ProgramStartJobber',
        ),
    ]
