# Generated by Django 6.0.3 on 2026-04-01 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_greigepurchaseorder_greigepurchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarnpurchaseorderitem',
            name='material_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'material_kind': 'yarn'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='yarn_po_items', to='accounts.materialtype'),
        ),
        migrations.AlterField(
            model_name='yarnpurchaseorderitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='yarn_po_items', to='accounts.material'),
        ),
    ]
