# Generated by Django 6.0.3 on 2026-04-16 16:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_programstart_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('accessory_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('process_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expense_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wastage_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('target_margin_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('target_selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('bom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costing_snapshots', to='accounts.bom')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costing_snapshots', to='accounts.program')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_code', models.CharField(max_length=40, unique=True)),
                ('stage', models.CharField(choices=[('yarn', 'Yarn'), ('greige', 'Greige'), ('dyeing', 'Dyeing'), ('ready', 'Ready')], default='ready', max_length=20)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('dye_lot_no', models.CharField(blank=True, default='', max_length=80)),
                ('batch_no', models.CharField(blank=True, default='', max_length=80)),
                ('shade_reference', models.CharField(blank=True, default='', max_length=120)),
                ('location_name', models.CharField(blank=True, default='', max_length=120)),
                ('received_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('accepted_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rejected_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hold_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('used_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('available_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qc_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('partial', 'Partial'), ('hold', 'Hold'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_closed', models.BooleanField(default=False)),
                ('dyeing_inward_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_lots', to='accounts.dyeingpoinwarditem')),
                ('greige_inward_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_lots', to='accounts.greigepoinwarditem')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lots', to='accounts.material')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ready_inward_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_lots', to='accounts.readypoinwarditem')),
                ('yarn_inward_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_lots', to='accounts.yarnpoinwarditem')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=50)),
                ('length_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('gsm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('weight_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('accepted_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('partial', 'Partial'), ('hold', 'Hold'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='accounts.inventorylot')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('lot', 'roll_no')},
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_no', models.CharField(max_length=40, unique=True)),
                ('movement_type', models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('return', 'Return'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment'), ('dispatch', 'Dispatch')], default='receipt', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('movement_date', models.DateField(default=django.utils.timezone.localdate)),
                ('ref_model', models.CharField(blank=True, default='', max_length=80)),
                ('ref_number', models.CharField(blank=True, default='', max_length=80)),
                ('remarks', models.TextField(blank=True, default='')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='accounts.inventorylot')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='accounts.inventoryroll')),
            ],
            options={
                'ordering': ['-movement_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_started', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='start_record', to='accounts.program')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramStartFabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('count', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pp_count', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lot_no', models.CharField(blank=True, default='', max_length=150)),
                ('lot_count', models.PositiveIntegerField(default=0)),
                ('available_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('used_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_start_fabrics', to='accounts.material')),
                ('start_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_rows', to='accounts.programstart')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_start_fabrics', to='accounts.materialunit')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramStartJobber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobber_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allocation_date', models.DateField(blank=True, null=True)),
                ('invoice_no', models.CharField(blank=True, default='', max_length=100)),
                ('invoice_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('jobber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_start_jobbers', to='accounts.jobber')),
                ('jobber_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_start_jobber_types', to='accounts.jobbertype')),
                ('start_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobber_rows', to='accounts.programstart')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramStartSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=20)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('start_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_rows', to='accounts.programstart')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QRCodeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_code', models.CharField(max_length=60, unique=True)),
                ('qr_type', models.CharField(choices=[('lot', 'Lot'), ('roll', 'Roll')], default='lot', max_length=20)),
                ('status', models.CharField(default='active', max_length=20)),
                ('payload_url', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='accounts.inventorylot')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='accounts.inventoryroll')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qc_number', models.CharField(max_length=40, unique=True)),
                ('stage', models.CharField(choices=[('yarn', 'Yarn'), ('greige', 'Greige'), ('dyeing', 'Dyeing'), ('ready', 'Ready')], default='ready', max_length=20)),
                ('inspection_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('partial', 'Partial'), ('hold', 'Hold'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quality_checks', to=settings.AUTH_USER_MODEL)),
                ('dyeing_inward_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checks', to='accounts.dyeingpoinwarditem')),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_quality_checks', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='accounts.inventorylot')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ready_inward_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_checks', to='accounts.readypoinwarditem')),
                ('roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='accounts.inventoryroll')),
            ],
            options={
                'ordering': ['-inspection_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheckDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_name', models.CharField(max_length=120)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('affected_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('quality_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='accounts.qualitycheck')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheckParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=120)),
                ('expected_value', models.CharField(blank=True, default='', max_length=120)),
                ('actual_value', models.CharField(blank=True, default='', max_length=120)),
                ('tolerance', models.CharField(blank=True, default='', max_length=60)),
                ('is_pass', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('quality_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='accounts.qualitycheck')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
