# Generated by Django 6.0.3 on 2026-04-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_yarnpurchaseorderitem_material_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='greigepurchaseorder',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='greigepurchaseorder',
            name='available_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='greigepurchaseorder',
            name='cancel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greigepurchaseorder',
            name='delivery_period',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='greigepurchaseorder',
            name='delivery_schedule',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='greigepurchaseorder',
            name='director',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='greigepurchaseorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='greigepurchaseorder',
            name='internal_po_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='greigepurchaseorder',
            name='shipping_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='greigepurchaseorder',
            name='validity_period',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
