# Generated by Django 6.0.3 on 2026-04-17 09:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_costingsnapshot_inventorylot_inventoryroll_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramJobberChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challan_no', models.CharField(max_length=30, unique=True)),
                ('challan_date', models.DateField(default=django.utils.timezone.localdate)),
                ('production_sku', models.CharField(blank=True, default='', max_length=120)),
                ('product_name', models.CharField(blank=True, default='', max_length=180)),
                ('total_issued_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('inward_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('driver_name', models.CharField(blank=True, default='', max_length=120)),
                ('lr_no', models.CharField(blank=True, default='', max_length=80)),
                ('transport_name', models.CharField(blank=True, default='', max_length=150)),
                ('vehicle_no', models.CharField(blank=True, default='', max_length=50)),
                ('gate_pass_no', models.CharField(blank=True, default='', max_length=80)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('partial', 'Partial Inward'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_program_jobber_challans', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_jobber_challans', to='accounts.firm')),
                ('jobber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_jobber_challans', to='accounts.jobber')),
                ('jobber_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_jobber_challan_types', to='accounts.jobbertype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobber_challans', to='accounts.program')),
                ('start_jobber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challans', to='accounts.programstartjobber')),
                ('start_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobber_challans', to='accounts.programstart')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramJobberChallanSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=20)),
                ('issued_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('inward_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_rows', to='accounts.programjobberchallan')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
