# Generated by Django 6.0.3 on 2026-04-17 18:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_programjobberchallan_programjobberchallansize'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_no', models.CharField(max_length=30)),
                ('invoice_date', models.DateField(default=django.utils.timezone.localdate)),
                ('vehicle_no', models.CharField(blank=True, default='', max_length=50)),
                ('remarks', models.TextField(blank=True, default='')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('after_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_invoices', to='accounts.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_invoices', to='accounts.firm')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounts.program')),
            ],
            options={
                'ordering': ['-invoice_date', '-id'],
                'unique_together': {('owner', 'invoice_no')},
            },
        ),
        migrations.CreateModel(
            name='ProgramInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_label', models.CharField(blank=True, default='', max_length=80)),
                ('sku', models.CharField(blank=True, default='', max_length=120)),
                ('challan_no', models.CharField(blank=True, default='', max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hsn_code', models.CharField(blank=True, default='', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('dispatch_challan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='accounts.dispatchchallan')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.programinvoice')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month_key', models.CharField(max_length=7)),
                ('inward_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expense_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate)),
                ('remarks', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month_key', '-id'],
                'unique_together': {('owner', 'month_key')},
            },
        ),
    ]
