# Generated by Django 6.0.3 on 2026-04-18 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_programinvoice_programinvoiceitem_maintenancerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobber',
            name='role',
        ),
    ]
