# Generated by Django 6.0.3 on 2026-04-07 18:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_dyeingpoinward_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['party_name']},
        ),
        migrations.RemoveField(
            model_name='firm',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='party',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='firm',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='firm_logos/'),
        ),
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='party',
            name='account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='party',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='party',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='firm',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='firm',
            name='account_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='firm',
            name='address_line',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='firm',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='firm',
            name='branch_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='firm',
            name='cin_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='firm',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='firm',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='firm',
            name='firm_type',
            field=models.CharField(choices=[('law_firm', 'Law Firm'), ('company', 'Company'), ('individual', 'Individual'), ('startup', 'Startup'), ('other', 'Other')], default='company', max_length=20),
        ),
        migrations.AlterField(
            model_name='firm',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='firm',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='firm',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='firm',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='firm',
            name='pincode',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='firm',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='firm',
            name='tan_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='firm',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MaterialSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_kind', models.CharField(blank=True, choices=[('yarn', 'Yarn'), ('greige', 'Greige'), ('finished', 'Finished'), ('trim', 'Trim')], db_index=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='accounts.materialtype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('owner', 'material_type', 'name')},
            },
        ),
        migrations.AddField(
            model_name='material',
            name='material_sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='accounts.materialsubtype'),
        ),
    ]
