# Generated by Django 6.0.3 on 2026-04-08 16:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_party_options_remove_firm_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarnpurchaseorder',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_yarn_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReadyPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('po_number', models.CharField(blank=True, default='', max_length=30)),
                ('po_date', models.DateField(default=django.utils.timezone.localdate)),
                ('internal_po_number', models.CharField(blank=True, default='', max_length=30)),
                ('available_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_address', models.CharField(blank=True, default='', max_length=255)),
                ('delivery_period', models.CharField(blank=True, default='', max_length=100)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('cancel_date', models.DateField(blank=True, null=True)),
                ('director', models.CharField(blank=True, default='', max_length=120)),
                ('validity_period', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('delivery_schedule', models.CharField(blank=True, default='', max_length=150)),
                ('remarks', models.TextField(blank=True, default='')),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ready_purchase_orders', to='accounts.firm')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source_dyeing_po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ready_pos', to='accounts.dyeingpurchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ready_purchase_orders', to='accounts.vendor')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReadyPOInward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inward_number', models.CharField(max_length=30, unique=True)),
                ('inward_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inwards', to='accounts.readypurchaseorder')),
            ],
            options={
                'ordering': ['-inward_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReadyPurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_name', models.CharField(max_length=150)),
                ('dyeing_name', models.CharField(blank=True, default='', max_length=150)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.readypurchaseorder')),
                ('source_dyeing_po_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_ready_items', to='accounts.dyeingpurchaseorderitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReadyPOInwardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('inward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.readypoinward')),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inward_items', to='accounts.readypurchaseorderitem')),
            ],
            options={
                'unique_together': {('inward', 'po_item')},
            },
        ),
    ]
