# Generated by Django 6.0.3 on 2026-04-18 10:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_party_full_name_party_alt_phone_party_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='party',
            unique_together={('owner', 'party_code'), ('owner', 'party_name')},
        ),
    ]
