# Generated by Django 6.0.3 on 2026-04-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_party_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='readypoinwarditem',
            name='accepted_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='readypoinwarditem',
            name='actual_gsm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='readypoinwarditem',
            name='actual_rolls',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='readypoinwarditem',
            name='actual_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='readypoinwarditem',
            name='hold_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='readypoinwarditem',
            name='qc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('partial', 'Partial'), ('hold', 'Hold'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='readypoinwarditem',
            name='received_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='readypoinwarditem',
            name='rejected_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
