# Generated by Django 6.0.3 on 2026-04-19 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_qrcoderecord_last_scanned_at_qrcoderecord_qr_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readypurchaseorderitem',
            name='finished_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ready_po_items', to='accounts.material'),
        ),
        migrations.AlterField(
            model_name='readypurchaseorder',
            name='source_dyeing_po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ready_pos', to='accounts.dyeingpurchaseorder'),
        ),
    ]
