# Generated by Django 6.0.3 on 2026-04-20 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_readypurchaseorderitem_finished_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programjobberchallan',
            name='last_inward_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programjobberchallan',
            name='last_inward_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='programjobberchallan',
            name='last_inward_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_jobber_challans', to='accounts.inwardtype'),
        ),
    ]
