# Generated by Django 6.0.3 on 2026-04-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_programjobberchallan_last_inward_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programjobberchallan',
            name='last_inward_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programjobberchallansize',
            name='accepted_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='programjobberchallansize',
            name='rejected_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
