# Generated by Django 6.0.3 on 2026-04-11 16:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_bom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_no', models.CharField(max_length=30)),
                ('program_date', models.DateField(default=django.utils.timezone.localdate)),
                ('total_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ratio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('damage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='accounts.bom')),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='accounts.firm')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-program_date', '-id'],
                'unique_together': {('owner', 'program_no')},
            },
        ),
        migrations.CreateModel(
            name='ProgramJobberItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobber_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('issue_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('inward_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('jobber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_jobber_items', to='accounts.jobber')),
                ('jobber_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_jobber_items', to='accounts.jobbertype')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobber_items', to='accounts.program')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramSizeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('3XL', '3XL'), ('4XL', '4XL'), ('5XL', '5XL')], max_length=10)),
                ('cq', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fq', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dq', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fq_dq', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_details', to='accounts.program')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('program', 'size')},
            },
        ),
    ]
