# Generated by Django 6.0.3 on 2026-04-21 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_readypurchaseorder_approval_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_items', to='accounts.expense')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='accounts.maintenancerecord')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
