# Generated by Django 6.0.3 on 2026-04-13 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_location_address_remove_location_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarnpoinward',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yarn_inwards', to='accounts.vendor'),
        ),
    ]
