# Generated by Django 6.0.3 on 2026-04-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_maintenanceexpenseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='programstartjobber',
            name='assigned_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
