# Generated by Django 6.0.3 on 2026-04-23 18:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_programstartjobber_assigned_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='greigepurchaseorder',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='greigepurchaseorder',
            name='terms_conditions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='readypurchaseorder',
            name='terms_conditions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='yarnpurchaseorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yarnpurchaseorder',
            name='internal_po_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='yarnpurchaseorder',
            name='po_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.CreateModel(
            name='DispatchChallanSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('dispatch_challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_rows', to='accounts.dispatchchallan')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('dispatch_challan', 'size_name')},
            },
        ),
    ]
