# Generated by Django 6.0.3 on 2026-04-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_erpnotification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='erpnotification',
            new_name='accounts_er_owner_i_d861b6_idx',
            old_name='accounts_er_owner_i_3e6458_idx',
        ),
        migrations.RenameIndex(
            model_name='erpnotification',
            new_name='accounts_er_owner_i_1b640e_idx',
            old_name='accounts_er_owner_k_0d4c1d_idx',
        ),
    ]
