# Generated by Django 6.0.3 on 2026-04-13 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_greigepurchaseorder_source_yarn_inward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='greigepurchaseorder',
            options={},
        ),
        migrations.RemoveField(
            model_name='greigepurchaseorder',
            name='firm',
        ),
        migrations.RemoveField(
            model_name='greigepurchaseorder',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='greigepurchaseorder',
            name='total_weight',
        ),
        migrations.CreateModel(
            name='DyeingOtherCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
