# Generated by Django 6.0.3 on 2026-04-14 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_inwardtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yarnpoinward',
            options={},
        ),
        migrations.AddField(
            model_name='yarnpoinward',
            name='inward_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yarn_inwards', to='accounts.inwardtype'),
        ),
    ]
