# Generated by Django 6.0.3 on 2026-05-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_product_tenant_role_permissions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_company_54fc08_idx',
            old_name='accounts_au_company_a2c894_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_owner_i_dbe8a9_idx',
            old_name='accounts_au_owner_3c65ae_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_actor_i_48e6fd_idx',
            old_name='accounts_au_actor_824dda_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_action_f18cdc_idx',
            old_name='accounts_au_action_d914c9_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_severit_c4c321_idx',
            old_name='accounts_au_severit_5ab333_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_object__109e82_idx',
            old_name='accounts_au_object__663ce6_idx',
        ),
    ]
