# Generated by Django 6.0.3 on 2026-04-14 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_inwardtype_and_yarnpoinward_inward_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomexpenseitem',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_expense_items', to='accounts.expense'),
        ),
        migrations.AlterField(
            model_name='bomexpenseitem',
            name='expense_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
