# Generated by ChatGPT for Ready PO yarn-style item details

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0044_rename_accounts_au_company_a2c894_idx_accounts_au_company_54fc08_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="readypurchaseorderitem",
            name="value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="readypurchaseorderitem",
            name="dia",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="readypurchaseorderitem",
            name="gauge",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="readypurchaseorderitem",
            name="rolls",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="readypurchaseorderitem",
            name="count",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="readypurchaseorderitem",
            name="gsm",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="readypurchaseorderitem",
            name="sl",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="readypurchaseorderitem",
            name="hsn_code",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="readypurchaseorderitem",
            name="rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="readypurchaseorderitem",
            name="final_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
