# Generated by Django 6.0.3 on 2026-04-14 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='catalogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boms', to='accounts.catalogue'),
        ),
        migrations.AddField(
            model_name='bom',
            name='sub_category_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boms', to='accounts.subcategory'),
        ),
        migrations.CreateModel(
            name='BOMImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bom/gallery/%Y/%m/')),
                ('caption', models.CharField(blank=True, default='', max_length=150)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.bom')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
