# Generated by Django 6.0.3 on 2026-04-14 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_bom_catalogue_bom_sub_category_master_bomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dyeingpurchaseorder',
            name='source_greige_inward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_dyeing_pos', to='accounts.greigepoinward'),
        ),
    ]
