# Generated by Django 6.0.3 on 2026-04-14 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_greigepurchaseorder_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bom',
            unique_together={('owner', 'sku_code')},
        ),
        migrations.AddField(
            model_name='bom',
            name='color_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bom',
            name='size_chart_image',
            field=models.ImageField(blank=True, null=True, upload_to='bom/size_chart/%Y/%m/'),
        ),
    ]
