# Generated by Django 6.0 on 2026-01-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_material_options_remove_material_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finisheddetail',
            name='base_fabric_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='finisheddetail',
            name='finish_type',
            field=models.CharField(blank=True, choices=[('dyed', 'Dyed'), ('printed', 'Printed'), ('coated', 'Coated'), ('washed', 'Washed'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='greigedetail',
            name='fabric_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='trimdetail',
            name='trim_type',
            field=models.CharField(blank=True, choices=[('Button', 'Button'), ('Zipper', 'Zipper'), ('Label', 'Label'), ('Elastic', 'Elastic'), ('Thread', 'Thread'), ('Hook', 'Hook'), ('Other', 'Other')], max_length=80),
        ),
        migrations.AlterField(
            model_name='yarndetail',
            name='yarn_type',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
