# Generated by Django 6.0 on 2026-01-08 07:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_materialtype_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialshade',
            options={},
        ),
        migrations.AlterModelOptions(
            name='materialtype',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='materialshade',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='materialtype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='materialshade',
            name='material_kind',
            field=models.CharField(blank=True, choices=[('yarn', 'Yarn'), ('greige', 'Greige'), ('finished', 'Finished'), ('trim', 'Trim')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='materialshade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='materialtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='materialshade',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='materialshade',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialshade',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='material_kind',
            field=models.CharField(blank=True, choices=[('yarn', 'Yarn'), ('greige', 'Greige'), ('finished', 'Finished'), ('trim', 'Trim')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
