# Generated by Django 6.0 on 2026-02-20 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_materialshade_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YarnPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_seq', models.PositiveIntegerField(db_index=True, default=0)),
                ('po_no', models.CharField(db_index=True, max_length=30)),
                ('internal_po_no', models.CharField(blank=True, default='', max_length=50)),
                ('po_date', models.DateField()),
                ('cancel_date', models.DateField(blank=True, null=True)),
                ('director', models.CharField(blank=True, default='', max_length=120)),
                ('address', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('terms_conditions', models.TextField(blank=True, default='')),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('after_discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('others', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tcs_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tcs_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yarn_po_approved', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yarn_pos', to='accounts.firm')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yarn_pos', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yarn_po_rejected', to=settings.AUTH_USER_MODEL)),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yarn_pos_ship_to', to='accounts.location')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yarn_pos', to='accounts.party')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('owner', 'po_no'), ('owner', 'po_seq')},
            },
        ),
        migrations.CreateModel(
            name='YarnPurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('MTR', 'MTR'), ('KG', 'KG'), ('PCS', 'PCS')], default='MTR', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dia', models.CharField(blank=True, default='', max_length=20)),
                ('gauge', models.CharField(blank=True, default='', max_length=20)),
                ('rolls', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('count', models.CharField(blank=True, default='', max_length=30)),
                ('gsm', models.CharField(blank=True, default='', max_length=30)),
                ('sl', models.CharField(blank=True, default='', max_length=30)),
                ('hsn_code', models.CharField(blank=True, default='', max_length=30)),
                ('remark', models.CharField(blank=True, default='', max_length=250)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yarn_po_items', to='accounts.material')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.yarnpurchaseorder')),
            ],
        ),
    ]
